vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        recipes:
            uri_prefix: /upload/recipes
            upload_destination: '%kernel.project_dir%/public/upload/recipes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
